MvcApiTokenCubosCMA/Models/BlobModel.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class BlobModel
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Contenedor { get; set; }
    }
}

MvcApiTokenCubosCMA/Models/Cubo.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class Cubo
    {
        public int IdCubo { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Imagen { get; set; }
        public int Precio { get; set; }
    }
}

MvcApiTokenCubosCMA/Models/ErrorViewModel.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiTokenCubosCMA/Models/LoginModel.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class LoginModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

MvcApiTokenCubosCMA/Models/Pedido.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class Pedido
    {
        public int IdPedido { get; set; }
        public int IdCubo { get; set; }
        public int IdUsuario { get; set; }
        public DateTime FechaPedido { get; set; }
    }
}

MvcApiTokenCubosCMA/Models/Usuario.cs
namespace MvcApiTokenCubosCMA.Models
{
    public class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Imagen { get; set; }
    }
}

MvcApiTokenCubosCMA/Controllers/CubosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiTokenCubosCMA.Filters;
using MvcApiTokenCubosCMA.Models;
using MvcApiTokenCubosCMA.Services;

namespace MvcApiTokenCubosCMA.Controllers
{
    public class CubosController : Controller
    {
        private ServiceApiCubos service;

        public CubosController(ServiceApiCubos service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Cubo> cubos =
                await this.service.GetCubosAsync();
            return View(cubos);
        }

        public async Task<IActionResult> CubosPorMarca(string marca)
        {
            if(marca == null)
            {
                ViewData["MENSAJE"] = "Inserte Marca";
                return View();
            }
            else
            {
                List<Cubo> cubo =
                    await this.service.FindCuboAsync(marca);
                return View(cubo);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cubo cubo)
        {
            await this.service.InsertCuboAsync
                (cubo.Nombre, cubo.Marca, cubo.Imagen, cubo.Precio);
            return RedirectToAction("Index");
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(Usuario user)
        {
            await this.service.CrearUsuarioAsync
                (user.Nombre, user.Email, user.Pass, user.Imagen);
            return RedirectToAction("Index", "Home");
        }

        [AuthorizeCubos]
        public async Task<IActionResult> PerfilUsuario()
        {
            string token =
            HttpContext.Session.GetString("TOKEN");
            if (token == null)
            {
                ViewData["MENSAJE"] = "Debe realizar Login para visualizar datos";
                return View();
            }
            else
            {
                Usuario user =
                    await this.service.FindUsuarioAsync(token);
                return View(user);
            }
        }

        [AuthorizeCubos]
        public async Task<IActionResult> PedidosUsuario()
        {
            string token =
            HttpContext.Session.GetString("TOKEN");
            if (token == null)
            {
                ViewData["MENSAJE"] = "Debe realizar Login para visualizar datos";
                return View();
            }
            else
            {
                List<Pedido> pedidos =
                    await this.service.FindPedidosAsync(token);
                return View(pedidos);
            }
        }
    }
}

MvcApiTokenCubosCMA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiTokenCubosCMA.Models;
using System.Diagnostics;

namespace MvcApiTokenCubosCMA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiTokenCubosCMA/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcApiTokenCubosCMA.Models;
using MvcApiTokenCubosCMA.Services;
using System.Security.Claims;

namespace MvcApiTokenCubosCMA.Controllers
{
    public class ManagedController : Controller
    {
        private ServiceApiCubos service;

        public ManagedController(ServiceApiCubos service)
        {
            this.service = service;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login
        (string email, string password)
        {
            string token =
                await this.service.GetTokenAsync(email, password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
            else
            {
                ViewData["MENSAJE"] = "Bienvenid@ a mi App!!!";
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity
                    (CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.Name, email));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, password));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , userPrincipal, new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                    });
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcApiTokenCubosCMA/Views/Cubos/Create.cshtml
@model MvcApiTokenCubosCMA.Models.Cubo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cubo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Cubos">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiTokenCubosCMA/Views/Cubos/CreateUser.cshtml
@model MvcApiTokenCubosCMA.Models.Usuario

@{
    ViewData["Title"] = "CreateUser";
}

<h1>Create User</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pass" class="control-label"></label>
                <input asp-for="Pass" class="form-control" />
                <span asp-validation-for="Pass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-contoller="Home">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiTokenCubosCMA/Views/Cubos/CubosPorMarca.cshtml
@model IEnumerable<MvcApiTokenCubosCMA.Models.Cubo>

@{
    ViewData["Title"] = "CubosPorMarca";
}

<h1>Cubos Por Marca</h1>

<form method="post">
    <label>Buscar por marca:</label>
    <input type="text" name="marca" class="form-control" />
    <button class="btn btn-info">Buscar</button>
</form>

@if(Model != null)
{
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCubo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCubo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
        </tr>
}
    </tbody>
</table>
}else{
    <h1 style="color:red">@ViewData["MENSAJE"]</h1>
}

MvcApiTokenCubosCMA/Views/Cubos/Index.cshtml
@model IEnumerable<MvcApiTokenCubosCMA.Models.Cubo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controller="Cubos">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCubo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCubo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiTokenCubosCMA/Views/Cubos/PedidosUsuario.cshtml
@model IEnumerable<MvcApiTokenCubosCMA.Models.Pedido>

@{
    ViewData["Title"] = "PedidosUsuario";
}

<h1>Pedidos Usuario</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPedido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCubo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPedido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCubo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPedido)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiTokenCubosCMA/Views/Cubos/PerfilUsuario.cshtml
@model MvcApiTokenCubosCMA.Models.Usuario

@{
    ViewData["Title"] = "PerfilUsuario";
}

<h1>Perfil Usuario</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcApiTokenCubosCMA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiTokenCubosCMA/Views/Managed/Login.cshtml
<h1>Login</h1>


<form method="post">
    <label>Usuario</label>
    <input type="text" name="email" placeholder="Email"
        class="form-control" />
    <label>Password</label>
    <input type="text" name="password" placeholder="Password"
        class="form-control" />
        <button class="btn btn-info">Log In</button>
</form>

<h2 style="color: red">
    @ViewData["MENSAJE"]
</h2>

MvcApiTokenCubosCMA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiTokenCubosCMA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiTokenCubosCMA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiTokenCubosCMA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcApiTokenCubosCMA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcApiTokenCubosCMA/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated){
    <li class="nav-item">
        <a class="nav-link text-danger"
       asp-controller="Cubos"
       asp-action="Index">
            Cubos
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-danger"
           asp-controller="Cubos"
           asp-action="CubosPorMarca">
            Cubos Marca
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Cubos"
            asp-action="PerfilUsuario">
            Perfil Usuario
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Cubos"
            asp-action="PedidosUsuario">
            Pedidos Usuario
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
       asp-controller="Managed"
       asp-action="Logout">
            Log Out
            <span style="color:blue">@Context.User.Identity.Name</span>
        </a>
    </li>
}else{
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Cubos"
            asp-action="CreateUser">
            Crear Usuario
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Managed"
            asp-action="Login">
            Log In
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Cubos"
            asp-action="PerfilUsuario">
            Perfil Usuario
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Cubos"
            asp-action="PedidosUsuario">
            Pedidos Usuario
        </a>
    </li>
}